language: python

python:
    - "2.5"
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"

matrix:
  allow_failures:
    - python: "pypy"
    - python: "3.2"
    - python: "3.3"

install:
    - python setup.py install

script:
    - py.test
